### PR TITLE
Variable name and node path generation refactoring

### PR DESCRIPTION
**Pull request by DarkMessiah**
- Variable names generation became more universal.
- Node path generation made by method 'path_to' instead of 'split'.

### CODE REVIEW

**Review by SanderVanhove — CHANGES_REQUESTED** [review]
Hey! Thanks for the PR again. I like how you did the new node path. 

But I don't agree with the variable name, I don't want it to be capitalized because it is not a `const`.

**Comment by DarkMessiah** [comment]
What does it mean not a `const`? 

Edit: In godot 4 you can change node's name casing in settings. Here example of naming: https://github.com/godotengine/godot/blob/master/editor/plugins/canvas_item_editor_plugin.cpp#L5477

https://docs.godotengine.org/en/stable/classes/class_string.html#class-string-method-capitalize

Edit 2: `var name := node.name.capitalize().replace(" ", "_").to_lower()` variable name doesn't become uppercased, here `to_lower` in the end. `capitalized` need only for splitting.

**Comment by SanderVanhove** [comment]
Oh ok, I see, didn't see the `to_lower` there, excuse me 😅  I was just looking at the code, will try it out as soon as I can and will get back after 😄

**Comment by DarkMessiah** [comment]
Hehe, https://github.com/godotengine/godot/pull/60879 :)

**Comment by SanderVanhove** [comment]
> Hehe, [godotengine/godot#60879](https://github.com/godotengine/godot/pull/60879) :)

Oh, that would actually be great! 😄

**Pull request merged**
