### PR TITLE
Updating script without reopening

### PR DESCRIPTION
**Pull request by DarkMessiah**
Hello :) Now the script is updated on save.

### CODE REVIEW

**Comment by SanderVanhove** [comment]
Oh cool! I will check it out 😄 Thanks for the PR!

**Comment by SanderVanhove** [comment]
Hey @DarkMessiah,

I checked it out. I interpreted your explanation as "The script in the editor will automatically show the reference so you don't have to close and reopen it." But I can't seem to replicate this behavior. 😕 

What does happen for me now is that I can `Alt + Tab` away from the Godot Editor and when I come back the script is updated 🤗 

Could you elaborate a little on what exactly you added/the new saving behavior is? I would be great if we could figure this out 😄

**Comment by DarkMessiah** [comment]
Hey @SanderVanhov,

Resource is ref-counted in Godot. When you use this code, you are changing same resource and Godot does not see difference between saved and loaded script.

```
func _save_script(script: Script) -> void:
	ResourceSaver.save(script.resource_path, script)
	script.emit_changed()
```

I reopened script file and saved new string, then I reloaded all scripts inside Script Editor (https://docs.godotengine.org/en/stable/classes/class_scripteditor.html)
```
func _save_script(script: Script) -> void:
	var file := File.new()
	file.open(script.resource_path, File.WRITE)
	file.store_string(script.source_code)
	file.close()
	get_editor_interface().get_script_editor().reload_scripts()
```

But now, I think, you can just duplicate script on save.
```
func _save_script(script: Script) -> void:
	ResourceSaver.save(script.resource_path, script.duplicate())
	get_editor_interface().get_script_editor().reload_scripts()
```

Sorry for my English :)

**Comment by SanderVanhove** [comment]
Thanks for clarifying that 😁 But it doesn't seem to work as described, the scripts don't get reloaded in my case 😕  Do they reload for you? What version of Godot are you using?

**Comment by DarkMessiah** [comment]
Oh sorry, it's my mistake. I use beta 3.5 and `reload_scripts()` it's a new method :'( In 3.4 it works only with `Alt + Tab` as you described.

**Comment by DarkMessiah** [comment]
Fixed pull request for both versions :) Can't find any workaround to reload script in 3.4.2 :'(
```
func _save_script(script: Script) -> void:
	ResourceSaver.save(script.resource_path, script.duplicate())
	# For version 3.5
	var script_editor := get_editor_interface().get_script_editor()
	if script_editor.has_method("reload_scripts"):
		script_editor.call("reload_scripts")
```

**Comment by SanderVanhove** [comment]
Awesome, thanks! I'll update once 3.5 is officially out 🤗

**Comment by SanderVanhove** [comment]
The new changes are also submitted to the Asset Library for validation :)

**Pull request merged**
